fix: import with type loader in admin assets route
Error loading route moError loading route module /app/routes/papa/admin/assets/index.tsx, reloading page.

SyntaxError: The requested module '/app/routes/papa/admin/assets/resource.ts' does not provide an export named 'loader'